version: "3"

services:
  nodejs-server:
    image: node:latest
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - "4000:4000"
    command: npm start

  react-app:
    image: node:latest
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    command: yarn start
